# Generated by Django 4.1.7 on 2023-03-31 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
