# Generated by Django 4.1.7 on 2023-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
